project:
  type: website
  output-dir: docs

website:
  title: "STATS 720 Portfolio â€” Konstantinos Banos"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Project 1"
        href: Project_1.qmd
      - text: "Project 2"
        href: Project_2.qmd
      - text: "Project 3"
        href: Project_3.qmd
      - text: "Project 4"
        href: Project_4.qmd
      - text: "Project 5"
        href: Project_5.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-line-numbers: true
  pdf:
    toc: true

execute:
  echo: true
  warning: false
  message: false

editor: visual



