project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - Project_4.qmd

website:
  title: "STATS 720 Portfolio â€” Konstantinos Banos"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Project 4"
        href: Project_4.html

format:
  html:
    theme: cosmo
    toc: true
    code-line-numbers: true

execute:
  echo: true
  warning: false
  message: false

editor: visual



